### ISSUE TITLE
Support for multiple columns in dimension keys

### ISSUE THREAD

**Issue by akariv** [openspending/babbage#6]
(Not sure if this is a real issue)

If FDP it's possible to define dimensions which span over multiple attributes in the source data. These dimensions can also have a primary key that contains multiple attributes (see: http://fiscal.dataprotocols.org/spec/#dimensions).

This makes sense, for example, with hierarchical classification systems (like in here: https://github.com/akariv/boost-peru-national/blob/master/datapackage.json#L246). The dimension spans over the 4 attributes which make up the administrative classification. 

In these cases, I'd expect the primary key to contain all the attributes in the hierarchy. However, it seems to me that right now babbage supports only one key per column, so that in the above case it would expect each of these administrative classification levels to be defined as a separate dimension.

So, in order to allow FDP to be imported into babbage we need to either:
- Adjust the dimensions in the FDP to have only one primary key. For example, in the above case, we would create 4 separate dimensions with names such as 'administrative_classification.Admin1' etc
- Add internal support in babbage for multi-column primary keys

wdyt?

**Comment by pudo** [comment]
I saw this in the FDP spec, and it boggles my mind a bit.

The reason babbage tries to name a key for each dimension is that a) it can be filtered for (e.g. in a query like ``?cuts=dimension:value``), and b) it can be used in URLs (e.g. ``/mybudget/programs/01/0192/0192918``). If we had star schema, it could feasibly be the join key as well (these might be separate, too).

All of these things get much harder if you make the key a tuple, and I wasn't at all clear about the use cases until you filed this issue. 

In your example, you're dealing with a hierarchy - something I'm really keen to have proper support for in babbage. Right now, the assumption is that all fields in a dimension are always the same tuple; they're assumed to be magically normalized. Support for hierarchies would push this assumption to the level of dimension levels.

As we add hierarchies and levels, we'll run into some variant of the multiple keys problem. One solution could be to force lower-level dimensions to come with identifiers which are globally unique, not just in the context of their parent level. The other one is to assume that an aggregation on level4 always either implies an aggregation or a filter to be applied on level3, level2 and level1. This seems the best approach to me at first glance.

As long as we don't have that support, I'd actually model these as different dimensions.

**Comment by pwalsh** [comment]
This is related to discussion with @danfowler and @rgrp right now.

* https://github.com/openspending/fiscal-data-package/issues/96
* https://github.com/openspending/fiscal-data-package/issues/99

In particular about identifiers, see my comments here: https://github.com/openspending/fiscal-data-package/issues/96#issuecomment-162598473

In a more general sense though, this area of the spec is *really* unclear for implementations, and while it pains me to agree at this stage ( as I strongly believe we are losing out by not addressing the sensibility of dimensions as attribute groups #99, and by not having a clear implementation path for hierarchies #99 ) the only option right now seems to be to model attributes in the data as distinct dimensions.

@akariv what would really help right now is if you could jump into those issues (or create new ones) and raise points there that are relevant to your work at present. I totally get that this issue is about what we can do in babbage, but we can make a clearer case for moving towards a star schema in babbage if we can have clarity in the spec that demonstrates the utility for data as published.

**Comment by pwalsh** [comment]
@akariv is there any action for this now that we have an fdp -> babbage loader working?

**Comment by rgrp** [comment]
Just to note I'm following this and it does indeed relate to the question of a) whether we normalize b) how we generate foreign key / primary key (on classification table).

I tend to be with @pudo here that we should generate a unique primary key and that was the approach suggest in the FDP spec.

**Comment by akariv** [comment]
Well, in this first iteration of the loader, all compound dimensions are separated according to their primary keys. For example, an 'administrative-level' dimension will be split into separate dimensions, one for each level.
I think that this is better in terms of simplicity and ease-of-use, but the during the process some of the context does gets lots - especially the hierarchy and other, non-key and non-label attributes which can't be assigned to any one of the split dimensions.

**Comment by pwalsh** [comment]
@akariv is this still relevant?

**Comment by akariv** [comment]
Hey, this was resolved in https://github.com/openspending/babbage/pull/8
